// Regenerates packages/ens/src/abi/humanosRegistrar.ts from the forge build output.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = JSON.parse(
  readFileSync(
    join(root, "out/HumanOSRegistrar.sol/HumanOSRegistrar.json"),
    "utf8",
  ),
);
const target = join(root, "../ens/src/abi/humanosRegistrar.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// Generated by packages/contracts/script/export-abi.mjs from HumanOSRegistrar. Do not edit.\n` +
    `export const humanosRegistrarAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
console.log(`wrote ${target}`);
