// Generated by packages/contracts/script/export-abi.mjs from HumanOSRegistrar. Do not edit.
export const humanosRegistrarAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct HumanOSRegistrar.Config",
        components: [
          {
            name: "factory",
            type: "address",
            internalType: "address",
          },
          {
            name: "userRegistryImplementation",
            type: "address",
            internalType: "address",
          },
          {
            name: "resolverImplementation",
            type: "address",
            internalType: "address",
          },
          {
            name: "parentRegistry",
            type: "address",
            internalType: "contract IPermissionedRegistry",
          },
          {
            name: "parentLabel",
            type: "string",
            internalType: "string",
          },
          {
            name: "parentSuffix",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
      {
        name: "initialOwner",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "CAPABILITIES_KEY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CAPABILITY_MASK",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FACTORY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract VerifiableFactory",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "HUMANOS_REGISTRY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPermissionedRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_AGENTS_PER_ROOT",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_ROOT_ID_LENGTH",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PARENT_NODE",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PARENT_REGISTRY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPermissionedRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RECEIPT_KEY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RESOLVER_IMPLEMENTATION",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ROOT_KEY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STATUS_KEY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "USER_REGISTRY_IMPLEMENTATION",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "authorization",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "a",
        type: "tuple",
        internalType: "struct HumanOSRegistrar.AgentAuthorization",
        components: [
          {
            name: "exists",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "active",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "revoked",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "rootNode",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "rootId",
            type: "string",
            internalType: "string",
          },
          {
            name: "name",
            type: "string",
            internalType: "string",
          },
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
          {
            name: "resolver",
            type: "address",
            internalType: "address",
          },
          {
            name: "capabilities",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "expiry",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "agentExpiry",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "rootExpiry",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "parentExpiry",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRootRevoked",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "narrowAgentCapabilities",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "capabilities",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "nodeUsed",
    inputs: [
      {
        name: "node",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "parentLabel",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "parentName",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerAgent",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "label",
        type: "string",
        internalType: "string",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "capabilities",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "expiry",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerRoot",
    inputs: [
      {
        name: "label",
        type: "string",
        internalType: "string",
      },
      {
        name: "rootId",
        type: "string",
        internalType: "string",
      },
      {
        name: "rootOwner",
        type: "address",
        internalType: "address",
      },
      {
        name: "expiry",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renewAgent",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "newExpiry",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renewRoot",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "newExpiry",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeAgent",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeRoot",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rootAgents",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32[]",
        internalType: "bytes32[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rootNodeOf",
    inputs: [
      {
        name: "rootIdHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rootRegistry",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPermissionedRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rootResolver",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AgentCapabilitiesNarrowed",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "capabilities",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentIdentityRevoked",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "rootNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentRegistered",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "rootNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "label",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "resolver",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "capabilities",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "expiry",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AgentRenewed",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "expiry",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RootIdentityRevoked",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RootRegistered",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "label",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "rootId",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "owner",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "registry",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "resolver",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "expiry",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RootRenewed",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "expiry",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AgentExpired",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "AgentRevoked",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "CapabilityEscalation",
    inputs: [
      {
        name: "current",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "requested",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "DNSDecodingFailed",
    inputs: [
      {
        name: "dns",
        type: "bytes",
        internalType: "bytes",
      },
    ],
  },
  {
    type: "error",
    name: "ExpiryExceedsParent",
    inputs: [
      {
        name: "expiry",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "parentExpiry",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "error",
    name: "ExpiryNotInFuture",
    inputs: [
      {
        name: "expiry",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidAccount",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidCapabilities",
    inputs: [
      {
        name: "capabilities",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidLabel",
    inputs: [
      {
        name: "label",
        type: "string",
        internalType: "string",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidRootId",
    inputs: [],
  },
  {
    type: "error",
    name: "LabelAlreadyUsed",
    inputs: [
      {
        name: "label",
        type: "string",
        internalType: "string",
      },
    ],
  },
  {
    type: "error",
    name: "OffsetOutOfBoundsError",
    inputs: [
      {
        name: "offset",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "length",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "RootExpired",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "RootIdAlreadyRegistered",
    inputs: [],
  },
  {
    type: "error",
    name: "RootRevoked",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "StringsInsufficientHexLength",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "length",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "TooManyAgents",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UnknownAgent",
    inputs: [
      {
        name: "agentNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UnknownRoot",
    inputs: [
      {
        name: "rootNode",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
] as const;
