import { randomBytes, randomUUID } from 'node:crypto';
import { Hono, type Context } from 'hono';
import { getCookie,setCookie,deleteCookie } from 'hono/cookie';
import { bodyLimit } from 'hono/body-limit';
import * as v from 'valibot';
import { Database, type SessionRecord } from '@humanos/database';
import { hashCanonical, CreateMissionRequestSchema, AuthorizeMissionRequestSchema, VerifyWorldRequestSchema, type Mission,type ActionProposal,type Approval,type AuditEvent,type ExecutionReceipt,type JevAssessment,type PolicyDecision,type RootIdentity,type WorldProofRequest,type AgentAuthorization,type MissionProposal,type ActionProposalDraft } from '@humanos/schemas';
import {authorize,transition,POLICY_VERSION,classifyStatic} from '@humanos/policy';
import {JEV_MODEL,JEV_QUESTION_VERSION} from '@humanos/models';
import {approvalBinding,type createWorldVerifier} from '@humanos/world';
import {createExecutor,type ExecutionDependencies} from './services/execute-sensitive-action.js';
export interface EnsAdapter {register:(mission:Mission)=>Promise<string>;revoke:(mission:Mission)=>Promise<void>;readAuthorization:(name:string)=>Promise<AgentAuthorization>;}
export interface ApiConfig {db:Database;origin:string;world?:ReturnType<typeof createWorldVerifier>;models?:{proposeMission:(input:unknown)=>Promise<MissionProposal>;proposeNextAction:(input:unknown)=>Promise<ActionProposalDraft>;evaluate:(input:{mission:Mission;action:ActionProposal})=>Promise<JevAssessment>};ens?:EnsAdapter;effect?:ExecutionDependencies['effect'];flueUrl?:string;internalSecret?:string;}
type Env={Variables:{session:SessionRecord;root:RootIdentity}};
class HttpError extends Error {constructor(public status:400|401|403|404|409|410|503,public code:string,message=code){super(message);}}
function requireService<T>(service:T|undefined):T {if(!service)throw new HttpError(503,'INTEGRATION_UNAVAILABLE','This integration is not configured.');return service;}
export function createApi(config:ApiConfig){const {db}=config;const app=new Hono<Env>();
 app.use('*',bodyLimit({maxSize:100000}));
 app.use('*',async(c,next)=>{c.header('Cache-Control','no-store');c.header('X-Content-Type-Options','nosniff');if(!['GET','HEAD','OPTIONS'].includes(c.req.method)){const origin=c.req.header('origin');if((origin&&origin!==config.origin)||c.req.header('sec-fetch-site')==='cross-site')throw new HttpError(403,'FORBIDDEN');}await next();});
 const error=(c:Context,status:400|401|403|404|409|410|503,code:string,message:string)=>c.json({error:{code,message}},status);
 app.onError((e,c)=>{if(e instanceof HttpError)return error(c,e.status,e.code,e.message);if(e instanceof v.ValiError||e instanceof SyntaxError)return error(c,400,'INVALID_REQUEST','Invalid request data.');return error(c,503,'INTEGRATION_UNAVAILABLE','The operation could not be verified. No new authority was granted.');});
 async function session(c:Context):Promise<SessionRecord|null>{const token=getCookie(c,'humanos_session');if(!token)return null;const s=await db.get<SessionRecord>('sessions',hashCanonical(token));return s&&Date.parse(s.expiresAt)>Date.now()?s:null;}
 const cookieOpts={httpOnly:true,sameSite:'Strict' as const,secure:config.origin.startsWith('https:'),path:'/'};
 async function owner(c:Context,id:string):Promise<Mission>{const m=await db.get<Mission>('missions',id);const s=await session(c);if(!s)throw new HttpError(401,'UNAUTHENTICATED');if(!m||m.rootId!==s.rootId)throw new HttpError(404,'NOT_FOUND');return m;}
 async function ownedAction(c:Context){const a=await db.get<ActionProposal>('actions',c.req.param('id')??'');if(!a)throw new HttpError(404,'NOT_FOUND');await owner(c,a.missionId);return a;}
 async function detail(m:Mission){const actions=(await db.list<ActionProposal>('actions')).filter(a=>a.missionId===m.id);const ids=new Set(actions.map(a=>a.id));const evaluation=await db.get<{id:string;assessment:JevAssessment;decision:PolicyDecision}>('agents',`evaluation:${m.id}`);return {mission:m,actions,approvals:(await db.list<Approval>('approvals')).filter(p=>ids.has(p.actionId)),receipts:(await db.list<ExecutionReceipt>('receipts')).filter(r=>r.missionId===m.id),events:(await db.list<AuditEvent>('audit')).filter(e=>e.missionId===m.id),assessment:evaluation?.assessment??null,decision:evaluation?.decision??null};}
 async function audit(m:Mission,type:string,previousState:Mission['state']|null,metadata:AuditEvent['metadata']={}){await db.insert('audit',{id:randomUUID(),missionId:m.id,actionId:null,type,actor:m.rootId,previousState,nextState:m.state,policyVersion:POLICY_VERSION,modelVersions:{deepseek:'deepseek-flash',jev:JEV_MODEL},metadata,createdAt:new Date().toISOString()} satisfies AuditEvent);}
 app.get('/api/health',c=>c.json({status:'ok'}));
 app.get('/api/ready',c=>{const services=[['World ID',!!config.world],['DeepSeek and Jev',!!config.models],['ENSv2 Sepolia',!!config.ens],['Protected submission',!!config.effect],['Flue runtime',!!config.flueUrl]] as const;return c.json({ready:services.every(([,ready])=>ready),services:services.map(([name,ready])=>({name,ready,reason:ready?null:'Configuration or credentials required'}))});});
 app.get('/api/session',async c=>{const s=await session(c);return c.json({root:s?await db.get<RootIdentity>('roots',s.rootId):null});});
 app.post('/api/session/logout',async c=>{const token=getCookie(c,'humanos_session');if(token)await db.delete('sessions',hashCanonical(token));deleteCookie(c,'humanos_session',{path:'/'});return c.json({root:null});});
 app.post('/api/world/root/request',async c=>{const world=requireService(config.world);const token=randomBytes(32).toString('hex');const request=world.createRequest('humanos-root',hashCanonical(token));await db.insert('challenges',{id:request.requestId,request,ownerHash:hashCanonical(token),kind:'root',expiresAt:new Date(Number(request.rpContext.expires_at)*1000).toISOString(),consumedAt:null});setCookie(c,'humanos_challenge',token,{...cookieOpts,maxAge:300});return c.json(request);});
 app.post('/api/world/root/verify',async c=>{const input=v.parse(VerifyWorldRequestSchema,await c.req.json());const challenge=await db.get<{id:string;request:WorldProofRequest;ownerHash:string;kind:string}>('challenges',input.requestId);const token=getCookie(c,'humanos_challenge');if(!token||!challenge||challenge.kind!=='root'||challenge.ownerHash!==hashCanonical(token))throw new HttpError(403,'FORBIDDEN');const verified=await requireService(config.world).verify(challenge.request,input.proof);let root:RootIdentity={id:randomUUID(),ensName:null,createdAt:new Date().toISOString(),verificationEnvironment:challenge.request.environment};const sessionToken=randomBytes(32).toString('hex');await db.transaction(async tx=>{await tx.consumeChallenge(challenge.id,new Date());const existing=await tx.get<{id:string;rootId:string}>('nullifiers',verified.nullifierHash);if(existing){const known=await tx.get<RootIdentity>('roots',existing.rootId);if(!known)throw new HttpError(409,'CONFLICT');root=known;}else{await tx.insert('roots',root);await tx.claimNullifier(verified.nullifierHash,root.id);}await tx.insert('sessions',{id:hashCanonical(sessionToken),rootId:root.id,expiresAt:new Date(Date.now()+8*3600000).toISOString(),nullifier:verified.nullifier});});setCookie(c,'humanos_session',sessionToken,{...cookieOpts,maxAge:8*3600});deleteCookie(c,'humanos_challenge',{path:'/'});return c.json({root});});
 app.use('/api/missions/*',async(c,next)=>{const s=await session(c);if(!s)throw new HttpError(401,'UNAUTHENTICATED');c.set('session',s);await next();});
 app.use('/api/actions/*',async(c,next)=>{const s=await session(c);if(!s)throw new HttpError(401,'UNAUTHENTICATED');c.set('session',s);await next();});
 app.get('/api/missions',async c=>{const s=await session(c);if(!s)throw new HttpError(401,'UNAUTHENTICATED');return c.json({missions:(await db.list<Mission>('missions')).filter(m=>m.rootId===s.rootId)});});
 app.post('/api/missions',async c=>{const s=await session(c);if(!s)throw new HttpError(401,'UNAUTHENTICATED');const input=v.parse(CreateMissionRequestSchema,await c.req.json());const proposed=await requireService(config.models).proposeMission(input);const expiresAt=input.expiresAt??proposed.expiresAt;if(Date.parse(expiresAt)<=Date.now()||Date.parse(expiresAt)>Date.now()+86400000)throw new HttpError(400,'INVALID_REQUEST','Mission expiry must be within 24 hours.');const stamp=new Date().toISOString();const m:Mission={...proposed,goal:input.goal,expiresAt,id:randomUUID(),rootId:s.rootId,agentEns:null,state:'PROPOSED',approvedCapabilities:[],createdAt:stamp,updatedAt:stamp,policyVersion:POLICY_VERSION};await db.insert('missions',m);await audit(m,'MISSION_PROPOSED',null);return c.json(await detail(m),201);});
 app.get('/api/missions/:id',async c=>{let m=await owner(c,c.req.param('id'));if(Date.parse(m.expiresAt)<=Date.now()&&!['COMPLETED','REJECTED','EXPIRED','REVOKED','FAILED'].includes(m.state)){m=await db.transaction(async tx=>{const fresh=await tx.lockMission(m.id);const expired={...fresh,state:transition(fresh.state,'EXPIRE'),updatedAt:new Date().toISOString()};await tx.put('missions',expired);return expired;});}return c.json(await detail(m));});
 app.post('/api/missions/:id/authorize',async c=>{
  const m=await owner(c,c.req.param('id'));
  const input=v.parse(AuthorizeMissionRequestSchema,await c.req.json());
  const next=await db.transaction(async tx=>{
   const fresh=await tx.lockMission(m.id);
   if(fresh.state!=='PROPOSED'||Date.parse(fresh.expiresAt)<=Date.now()||input.approvedCapabilities.some(x=>!fresh.capabilities.includes(x)))throw new HttpError(409,'CONFLICT');
   const approved={...fresh,approvedCapabilities:[...input.approvedCapabilities]};
   // Serialize registration for this mission. The adapter must be idempotent across a DB rollback after chain submission.
   const registration=structuredClone(approved);Object.freeze(registration.capabilities);Object.freeze(registration.approvedCapabilities);Object.freeze(registration.steps);Object.freeze(registration);
   const agentEns=await requireService(config.ens).register(registration);
   const value={...approved,agentEns,state:transition(fresh.state,'AUTHORIZE'),updatedAt:new Date().toISOString()};await tx.put('missions',value);return value;
  });await audit(next,'MISSION_AUTHORIZED',m.state);return c.json(await detail(next));
 });
 app.post('/api/missions/:id/run',async c=>{const m=await owner(c,c.req.param('id'));const url=requireService(config.flueUrl);const next=await db.transaction(async tx=>{const fresh=await tx.lockMission(m.id);if(Date.parse(fresh.expiresAt)<=Date.now())throw new HttpError(410,'EXPIRED');const value={...fresh,state:fresh.state==='AUTHORIZED'?transition(fresh.state,'START'):fresh.state,updatedAt:new Date().toISOString()};if(value.state!=='RUNNING')throw new HttpError(409,'CONFLICT');await tx.put('missions',value);return value;});const response=await fetch(`${url}/agents/humanos/${encodeURIComponent(m.id)}`,{method:'POST',headers:{'content-type':'application/json',cookie:c.req.header('cookie')??''},body:JSON.stringify({kind:'user',body:'Prepare the next application or calendar action within my approved mission. Call prepare_next_action.'}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw new HttpError(503,'INTEGRATION_UNAVAILABLE','Flue did not accept the work. Retry to resume.');return c.json(await detail(next));});
 app.post('/api/missions/:id/revoke',async c=>{const m=await owner(c,c.req.param('id'));const next=await db.transaction(async tx=>{const fresh=await tx.lockMission(m.id);const next={...fresh,state:fresh.state==='REVOKED'?fresh.state:transition(fresh.state,'REVOKE'),updatedAt:new Date().toISOString()};await tx.put('missions',next);return next;});if(m.state!=='REVOKED')await audit(next,'MISSION_REVOKED',m.state);if(next.agentEns){await db.put('agents',{id:`revocation:${m.id}`,status:'PENDING'});await requireService(config.ens).revoke(next);await db.put('agents',{id:`revocation:${m.id}`,status:'CONFIRMED'});await audit(next,'ENS_REVOCATION_CONFIRMED',next.state);}return c.json(await detail(next));});
 app.post('/api/actions/:id/approval/request',async c=>{
  const a=await ownedAction(c);const s=await session(c);if(!s)throw new HttpError(401,'UNAUTHENTICATED');const world=requireService(config.world);
  const result=await db.withLockedAction(a.id,async(tx,action)=>{
   const currentSession=await tx.get<SessionRecord>('sessions',s.id);
   const m=await tx.get<Mission>('missions',action.missionId);const now=Date.now();
   if(!currentSession||Date.parse(currentSession.expiresAt)<=now||currentSession.rootId!==s.rootId)throw new HttpError(401,'UNAUTHENTICATED');
   if(!m||m.rootId!==s.rootId||action.rootId!==s.rootId)throw new HttpError(403,'FORBIDDEN');
   if(!['RUNNING','AWAITING_APPROVAL'].includes(m.state)||Date.parse(m.expiresAt)<=now||Date.parse(action.expiresAt)<=now)throw new HttpError(409,'CONFLICT');
   if(hashCanonical(action.payload)!==action.payloadHash)throw new HttpError(409,'CONFLICT');
   const binding=approvalBinding(action),bindingHash=hashCanonical(binding);
   const old=(await tx.list<Approval>('approvals')).find(p=>p.actionId===action.id);
   let approval:Approval;
   if(old){
    if(old.status!=='PENDING'||old.kind!=='WORLD_FRESH'||old.bindingHash!==bindingHash||hashCanonical(old.binding)!==bindingHash)throw new HttpError(409,'CONFLICT');
    const challenges=(await tx.list<{id:string;approvalId?:string;sessionId?:string;rootId?:string;actionId?:string;request:WorldProofRequest;expiresAt:string;consumedAt:string|null}>('challenges')).filter(r=>r.approvalId===old.id);
    if(!challenges.length||challenges.some(r=>r.sessionId!==s.id||r.rootId!==s.rootId||r.actionId!==action.id))throw new HttpError(403,'FORBIDDEN');
    const active=challenges.find(r=>!r.consumedAt&&Date.parse(r.expiresAt)>now&&r.request.action==='humanos-root'&&r.request.signal===bindingHash);
    if(active)return {approval:old,request:active.request};
    // Invalidate expired or legacy-scope requests even if their proofs remain cryptographically valid.
    for(const previous of challenges)if(!previous.consumedAt)await tx.query("UPDATE challenges SET data=jsonb_set(data,'{consumedAt}',to_jsonb($2::text)) WHERE id=$1 AND data->>'consumedAt' IS NULL",[previous.id,new Date(now).toISOString()]);
    approval=old;
   }else{
    approval={id:randomUUID(),actionId:action.id,binding,bindingHash,kind:'WORLD_FRESH',status:'PENDING',createdAt:new Date(now).toISOString(),verifiedAt:null,consumedAt:null,nullifierHash:null};
    await tx.insert('approvals',approval);
   }
   // World nullifiers are action-scoped. Keep the registered root action for same-human equality;
   // the exact operation is bound by this signal plus a fresh signed RP nonce and stored request ID.
   const request=world.createRequest('humanos-root',bindingHash);
   await tx.insert('challenges',{id:request.requestId,request,approvalId:approval.id,rootId:s.rootId,actionId:action.id,sessionId:s.id,kind:'approval',expiresAt:new Date(Math.min(Date.parse(action.expiresAt),Date.parse(m.expiresAt),Number(request.rpContext.expires_at)*1000)).toISOString(),consumedAt:null});
   if(m.state==='RUNNING')await tx.put('missions',{...m,state:transition(m.state,'REQUEST_APPROVAL'),updatedAt:new Date(now).toISOString()});
   return {approval,request};
  });return c.json(result);
 });
 app.post('/api/actions/:id/approval/verify',async c=>{const a=await ownedAction(c);const s=(await session(c))!;const input=v.parse(VerifyWorldRequestSchema,await c.req.json());const challenge=await db.get<{id:string;request:WorldProofRequest;approvalId:string;rootId:string;actionId:string;sessionId:string;kind:string}>('challenges',input.requestId);if(!challenge||challenge.kind!=='approval'||challenge.actionId!==a.id||challenge.rootId!==s.rootId||challenge.sessionId!==s.id)throw new HttpError(403,'FORBIDDEN');const verified=await requireService(config.world).verify(challenge.request,input.proof,String(s.nullifier));const next=await db.withLockedAction(a.id,async(tx)=>{await tx.consumeChallenge(challenge.id,new Date());await tx.updateApprovalStatus(challenge.approvalId,'VERIFIED',{verifiedAt:new Date().toISOString(),nullifierHash:verified.nullifierHash});const m=await tx.get<Mission>('missions',a.missionId);if(!m)throw new HttpError(404,'NOT_FOUND');const next={...m,state:transition(m.state,'APPROVE'),updatedAt:new Date().toISOString()};await tx.put('missions',next);return next;});await audit(next,'WORLD_APPROVAL_VERIFIED','AWAITING_APPROVAL',{actionId:a.id});return c.json(await detail(next));});
 app.post('/api/actions/:id/approval/cancel',async c=>{const a=await ownedAction(c);const m=await db.withLockedAction(a.id,async tx=>{const p=(await tx.list<Approval>('approvals')).find(p=>p.actionId===a.id);if(p)await tx.updateApprovalStatus(p.id,'CANCELLED');const m=await tx.get<Mission>('missions',a.missionId);if(!m)throw new HttpError(404,'NOT_FOUND');const next={...m,state:transition(m.state,'REJECT'),updatedAt:new Date().toISOString()};await tx.put('missions',next);return next;});return c.json(await detail(m));});
 app.post('/api/actions/:id/confirm',async c=>{const a=await ownedAction(c);if(classifyStatic(a)!=='CONSEQUENTIAL')throw new HttpError(403,'FORBIDDEN');await db.withLockedAction(a.id,async tx=>{const m=await tx.get<Mission>('missions',a.missionId);if(!m||m.state!=='RUNNING'||Date.parse(a.expiresAt)<=Date.now())throw new HttpError(409,'CONFLICT');const b=approvalBinding(a),stamp=new Date().toISOString();await tx.insert('approvals',{id:randomUUID(),actionId:a.id,binding:b,bindingHash:hashCanonical(b),kind:'CONSEQUENTIAL_CONFIRMATION',status:'VERIFIED',createdAt:stamp,verifiedAt:stamp,consumedAt:null,nullifierHash:null} satisfies Approval);});return c.json(await detail(await owner(c,a.missionId)));});
 app.post('/api/actions/:id/execute',async c=>{const a=await ownedAction(c);const executor=createExecutor({db,readAuthorization:requireService(config.ens).readAuthorization,evaluate:requireService(config.models).evaluate,effect:requireService(config.effect)});return c.json(await executor(a.id));});
 app.get('/api/internal/conversations/:id',async c=>{const m=await owner(c,c.req.param('id'));return c.json({mission:m});});
 app.post('/api/internal/missions/:id/prepare',async c=>{if(!config.internalSecret||c.req.header('authorization')!==`Bearer ${config.internalSecret}`)throw new HttpError(401,'UNAUTHENTICATED');const m=await db.get<Mission>('missions',c.req.param('id'));if(!m||m.state!=='RUNNING'||!m.agentEns)throw new HttpError(409,'CONFLICT');const models=requireService(config.models);const receipts=(await db.list<ExecutionReceipt>('receipts')).filter(r=>r.missionId===m.id);const draft=await models.proposeNextAction({mission:m,receipts});if(!['SUBMIT_APPLICATION','CREATE_CALENDAR_EVENT'].includes(draft.type))throw new HttpError(400,'INVALID_REQUEST','MVP supports application submission and calendar creation.');const existing=(await db.list<ActionProposal>('actions')).find(a=>a.missionId===m.id&&a.type===draft.type);if(existing)return c.json(await detail(m));if(draft.type==='CREATE_CALENDAR_EVENT'&&!receipts.some(r=>r.status==='SUCCEEDED'))throw new HttpError(409,'CONFLICT','Application must succeed before calendar creation.');const stamp=new Date().toISOString();const action:ActionProposal={...draft,id:randomUUID(),rootId:m.rootId,missionId:m.id,agentEns:m.agentEns,nonce:randomUUID(),payloadHash:hashCanonical(draft.payload),createdAt:stamp,expiresAt:new Date(Math.min(Date.parse(m.expiresAt),Date.now()+15*60000)).toISOString()};const assessment=await models.evaluate({mission:m,action});const authorization=await requireService(config.ens).readAuthorization(m.agentEns);const decision=authorize({mission:m,action,authorization,assessment,now:new Date(),pinnedJevModelVersion:JEV_MODEL,questionVersion:JEV_QUESTION_VERSION});if(!decision.allowed&&decision.reasons.some(reason=>reason!=='APPROVAL_REQUIRED'))throw new HttpError(403,'FORBIDDEN',decision.reasons.join(', '));await db.transaction(async tx=>{const fresh=await tx.lockMission(m.id);if(hashCanonical(fresh)!==hashCanonical(m))throw new HttpError(409,'CONFLICT');const duplicate=(await tx.list<ActionProposal>('actions')).find(a=>a.missionId===m.id&&a.type===action.type);if(!duplicate)await tx.insert('actions',action);await tx.put('agents',{id:`evaluation:${m.id}`,assessment,decision});});await audit(m,'ACTION_PREPARED',m.state,{actionId:action.id,payloadHash:action.payloadHash});return c.json(await detail(m));});
 return app;
}
