import { Database } from "../packages/database/src/index.js";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
const envFile = fileURLToPath(new URL("../.env", import.meta.url));
if (existsSync(envFile)) process.loadEnvFile(envFile);
const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL required");
const db = new Database(url);
await db.migrate();
await db.close();
console.log("HumanOS migrations applied");
